[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Pearl functionality
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if not inside then table.insert(pures, G.play.cards[i]) end"
position = "after"
payload = '''
elseif G.play.cards[i].ability.gemslot_pearl then
    local inside = false
    for j=1, #scoring_hand do
        if scoring_hand[j] == G.play.cards[i] then
            inside = true
        end
    end
    if not inside then table.insert(pures, G.play.cards[i]) end
'''
match_indent = true